#!/bin/bash -e
SOURCE_DIR=/var/lib/tsuru
add-apt-repository -y ppa:templateria/php
apt-get update
apt-get install -qqy nginx unzip php5-fpm php5-cli php5-mysqlnd php5-imagick php5-curl
wget https://github.com/wp-cli/builds/raw/gh-pages/deb/php-wpcli_0.14.0_all.deb -O /root/php-wpcli.deb
dpkg -i /root/php-wpcli.deb
rm -fr /root/php-wpcli.deb
echo 'alias wp="wp --path=/home/application/current/wordpress"' > /etc/profile.d/wp-cli.sh
echo "daemon off;" >> /etc/nginx/nginx.conf
